// packages/preview-svelte/src/components/home/index.svelte
<script lang="ts">
  import Router from "svelte-spa-router";
  import DemoHome from "~/components/demo-home/index.svelte";
  import { onMount } from "svelte";
  import { previewRouterExternals } from "@glue/glue-cli";
  import { replace } from "svelte-spa-router";
  export let lang: string;
  export let name: string;
  export let type: string;
  export let path: string;
  import { wrap } from "svelte-spa-router/wrap";
  console.log(lang, "langlanglang");
  let title;
  let showDocNav;
  $: {
    title = name ? name.replace(/-/g, "") : "";
    showDocNav = !previewRouterExternals.includes(path);
  }
  function onBack() {
    if (history.length > 1) {
      history.back();
    } else {
      replace("/");
    }
  }

  onMount(() => {
    window.addEventListener("message", (event) => {
      if (event.data?.type !== "replacePath") {
        return;
      }
      console.log(event.data, "event.data");
      const path = event.data?.value || "";
      replace(path);
    });
  });
  function syncPathToParent() {
    console.log(window.top, "window.top");
    if (window.top) {
      window.top.postMessage(
        {
          type: "replacePath",
          value: path,
        },
        "*"
      );
    }
  }
  const routes = {
    "/svelte/zh-CN/home": wrap({
      component: DemoHome,
      props: {
        name: `home`,
        path: "home",
        lang: lang,
        type: type,
      },
    }),
  };
</script>

{#if showDocNav}
  <glue-doc-nav gtitle={title} />
{/if}
<Router {routes} />

// packages/preview-solid/src/components/home/index.tsx
import { previewRouterExternals } from "@glue/glue-cli";
import { useRouteData, useNavigate } from "@solidjs/router";
import { Outlet } from "@solidjs/router";
import { Component, onMount } from "solid-js";

import { lazy } from "solid-js";
import { clearDelegatedEvents } from "solid-js/web";

const Home: Component = () => {
  interface IMeta {
    name: string;
    path: string;
    lang: string;
    type: string;
  }
  const { path, lang, name }: IMeta = useRouteData();
  console.log(path, lang, name, "routeData");

  const navigate = useNavigate();
  const title = name ? name.replace(/-/g, "") : "";
  const showDocNav = !previewRouterExternals.includes(name);
  console.log(showDocNav, title, name, "showDocNav");
  onMount(() => {
    window.addEventListener("message", (event) => {
      console.log("event.data?.type");
      if (event.data?.type !== "replacePath") {
        return;
      }

      const path = event.data?.value || "";
      console.log(event.data, path, "event.data");
      navigate(path);
    });
  });

  // useEffect(() => {
  //   //为啥会触发多次,很奇怪
  //   console.log(location, "1111111111");
  //   // syncPathToParent();
  // }, [location]);

  const onBack = () => {
    if (history.length > 1) {
      history.back();
    } else {
      navigate("/");
    }
  };
  function syncPathToParent() {
    console.log(window.top, "window.top");
    if (window.top) {
      window.top.postMessage(
        {
          type: "replacePath",
          value: path,
        },
        "*"
      );
    }
  }
  return (
    <div>
      {showDocNav ? (
        <glue-doc-nav gtitle={title} onGlueBack={onBack}></glue-doc-nav>
      ) : null}
      <Outlet></Outlet>
    </div>
  );
};

export default Home;
